service: oktank-serverless-demo

custom:
  stage: ${opt:stage, self:provider.stage}
  region: us-east-1
  memorySize: 512

provider:
  name: aws
  runtime: java8
  cfnRole: ${opt:cfnRoleArn}
  region: ${self:custom.region}
  memorySize: ${self:custom.memorySize}
  stackTags:
    "project": "AB3"
    "name": "oktank-serverless-demo"

package:
  artifact: target/oktank-serverless-demo-1.0-lambda-package.zip 

functions:
  pets:
    handler: com.oktank.serverless.demo.StreamLambdaHandler::handleRequest
    events:
      - http:
          path: /pets
          method: get
      - http:
          path: /pets
          method: post
    timeout: 30